### ISSUE TITLE
gulpfile.js中服务端代码保存自动刷新浏览器无效

### ISSUE THREAD

**Issue by mmming0821** [Selvin11/login#1]
gulpflile.js中 bs.reload()无效，node代码保存后，浏览器没有自动刷新
找到代码在这一块
// 延时刷新
gulp.task('bs-delay', function () {
  setTimeout(function () {
    bs.reload()
    console.log('重启完毕!')
  }, 2000)
})

**Comment by Selvin11** [comment]
是修改了哪个位置的文件呢

**Comment by mmming0821** [comment]
比如相对于server.js的./server/router/index.js文件中修改
    -res.send('Hello Express!')
    +res.send('Hello!')
控制台输出 '重启完毕' 没有报错，但浏览器仍需手动刷新才能看到 'Hello'
gulpfile.js代码:
// browser-sync 监听文件
gulp.task('server', ['browser-sync'], function () {
  gulp.watch(['./server.js', './server/**'], ['bs-delay'])
})
// 延时刷新
gulp.task('bs-delay', function () {
  setTimeout(function () {
    bs.reload()
    console.log('重启完毕!')
  }, 2000)
})
修改延迟时间也无效

**Comment by Selvin11** [comment]
这个你可以看下gulpfile.js中的browser-sync任务，它是针对4000端口的，因此3000端口的不会被刷新，其实这个项目请求的就是3000端口的数据接口，但是通过browser-sync代理在4000端口，4000端口会实时刷新 ，从而也会重新获取数据的

**Comment by mmming0821** [comment]
ts!
